"""empty message

Revision ID: 923fd32f4f7a
Revises: 
Create Date: 2023-11-29 07:16:13.893858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '923fd32f4f7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_hosts_id', table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address1', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address2', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('count_of_available_places', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_available_places', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hosts_pkey')
    )
    op.create_index('ix_hosts_id', 'hosts', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reached_limit', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('casemanager_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reservations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservations_pkey')
    )
    op.create_index('ix_reservations_id', 'reservations', ['id'], unique=False)
    # ### end Alembic commands ###
